w3c/fxtf-drafts

motion-1/Overview.bs, motion-1/Overview.html
fill-rule has been removed from the path function, which is used by offset-path.
Fixes issue #20
=> No fill-rule for Motion Path

motion-1/Overview.bs, motion-1/Overview.html
The computed value is an absolute value or a percentage, not the
specified value (which may be 'auto' or use em, vh, etc.
Resolves #37
=> [css-motion] Computed value of distance is absolute value or %

motion-1/Overview.bs, motion-1/Overview.html
As discussed in #41 and at TPAC, the initial value of
offset-anchor is center.
=> [css-motion] offset-anchor defaults to center

motion-1/Overview.bs, motion-1/Overview.html
Even when offset-path is the initial value (none), offset-position
can be used to position elements.
Resolves #47
=> [css-motion] offset-position creates a stacking context

motion-1/Overview.bs, motion-1/Overview.html
Distance is not bounded for <angle> paths without contain. We do not clamp or mod.
We clamp for <angle> paths with contain, and the "lower bound" is the negative of "upper bound".
Resolves #35.
=> [css-motion] Unbounded computed distance along <angle> paths

motion-1/Overview.bs, motion-1/Overview.html
Angle paths are now specified using ray functions, instead
of simple sequences of CSS values. This especially improves
readability when shorthands are used. (Note that offset-rotation
may also be an angle.)
Discussed in #42 and at TPAC.
geometry-box may not be used with a path.
=> [css-motion] offset-path syntax using ray()

motion-1/Overview.bs
* Clarify property description and cross-link to 'offset-path' which it references.
* Use a more precise description for the <<length-percentage>> value. TODO: The word "anchor point" should later be hyperlinked to a <dfn> instance under 'offset-anchor'.
* Use em-dash instead of hyphen, per English typographic rules.
* Use Bikeshed cross-reference syntax.
=> [motion] Editorial improvements to offset-distance

motion-1/Overview.bs
(This could probably use further improvement. Also ideally needs some text restored from an older version of CSS Values and Units L3.)
=> [motion-1] More precise definition of offset-position.

motion-1/Overview.bs, motion-1/Overview.html
Several of the ray() examples show unrotated boxes.
We now explicitly set the offset-rotation to 0deg, as the default
offset-rotation (auto) would cause rotation.
=> [motion] Prevent accidental rotation in examples

motion-1/Overview.bs, motion-1/Overview.html, motion-1/images/geometry-box.svg
The initial position and direction for geometry-box are the
same as for SVG rect: (x+rx,y) and to the right:
https://svgwg.org/svg2-draft/shapes.html#RectElement
Resolves #82
=> [motion] Initial position and direction for geometry-box

motion-1/Overview.bs, motion-1/Overview.html
The text was previously confused, for example saying "0deg points to the
right side in the direction of the positive y-axis".
As the initial value is 'auto', "offset-rotation isn’t specified" would
be equivalent to auto. The example in Figure 8 now uses '0deg' to avoid
rotation transformations.
=> [motion] offset-rotation is not a bearing.

motion-1/Overview.bs, motion-1/Overview.html
The description is now clearer, using text suggested by fantasai.
Resolves #63
=> [motion] <angle> notation should be defined as bearing angles

motion-1/Overview.bs, motion-1/Overview.html
As suggested by dbaron, the CSS Motion Path properties apply only
to transformable properties.
Resolves #58
=> [motion] properties apply only to transformable elements

motion-1/Overview.bs, motion-1/Overview.html
The properties must appear in specific order:
position path distance rotation / anchor
https://logs.csswg.org/irc.w3.org/css/2016-09-20/#e724237
There is one exception: distance and rotation may appear in either order.
The offset shorthand may simply contain a position.
https://logs.csswg.org/irc.w3.org/css/2016-09-20/#e724174
If offset-path is omitted, offset-distance and offset-rotation are not permitted.
The ambiguities in the original shorthand syntax are avoided:
- offset-distance is ambiguous with a position
offset-path always appears between offset-position and offset-distance.
/ always appears between offset-distance and offset-anchor.
- multiple properties have the value auto
offset-path must appear between offset-position and offset-rotation, if offset-position is auto.
/ always …
=> [css-motion] offset shorthand may be position / anchor

motion-1/Overview.bs, motion-1/Overview.html
We copy clip-path and shape-outside in using brackets around [ <<basic-shape> || <box> ], for clarity.
We also add brackets in the definition of offset-path, to make clear that
"contain) <size> ray(<angle>" and ") ray(<angle>" are not permitted expansions.
=> Use brackets in offset-path syntax

motion-1/Overview.bs, motion-1/Overview.html
offset-position is only used when offset-path is none and
offset-position is not auto. Otherwise, transform-origin is used.
Resolves #46
=> [motion] Clarify meaning of offset-anchor auto

motion-1/Overview.bs, motion-1/Overview.html, motion-1/images/geometry-box.svg
Creating a stacking context is not dependent on the reference resolving successfully.
The meaning of offset-rotate 'auto' has also been clarified: the direction of the path, relative to the positive x-axis. The "positive x-axis" terminology is copied from SVG:
https://www.w3.org/TR/SVG11/painting.html#OrientAttribute
https://www.w3.org/TR/SVG11/implnote.html#PathElementImplementationNotes
Example 12 now makes use of both 'auto' and 'reverse'.
resolves #65
=> [motion] Failed references treated as zero-length paths

motion-1/Overview.bs, motion-1/Overview.html
The descriptions of \<angle\>, \<size\> and 'contain' are now grouped under a single entry for ray.
This addresses the third editorial comment in #72
=> [motion] Group the parameters of ray

motion-1/Overview.bs, motion-1/Overview.html, motion-1/images/offset-initial.svg
The first airplane example in the offset-rotation section shows the placement of the airplane before any ``offset-*`` properties are applied.
Resolves #71
=> [motion] Airplane rotation example shows unrotated airplane

motion-1/Overview.bs, motion-1/Overview.html
When 'offset-path' is none, 'offset-distance' and 'offset-rotate' have
no effect.
See discussion in #64
=> No rotation when path is none

geometry/Overview.bs
Annotate setMatrixValue with [Exposed=Window] and throw TypeError
when DOMMatrix/DOMMatrixReadOnly is constructed with a string
if the current global is not a Window.
Fixes #122.
Tests: https://github.com/w3c/web-platform-tests/pull/5769
=> [geometry] Do not expose CSS parser in workers for DOMMatrix

geometry/Overview.bs
This should be editorial. It is a bit unclear from the definitions
of toFloat32Array() and toFloat64Array() if they could return the
same value, but it appears Chromium and Gecko return new values.
Tests: https://github.com/w3c/web-platform-tests/pull/5862
Fixes https://www.w3.org/Bugs/Public/show_bug.cgi?id=29541
=> [geometry] Annotate DOMMatrix's immutable methods with [NewObject]

motion-1/Overview.bs, motion-1/Overview.html
As discussed in the CSS Working Group, the issue about
offset-rotate syntax is being closed without change.
https://github.com/w3c/fxtf-drafts/issues/69#issuecomment-296087644
resolves #69
=> offset-rotate syntax is resolved

motion-1/Overview.bs, motion-1/Overview.html
The size argument of ray() is no longer optional.
The new keyword 'sides' indicates an angle-specific path length that
extends to the ray's intersection with the containing box.
Discussed in the CSS Working Group:
https://github.com/w3c/fxtf-drafts/issues/73#issuecomment-296084456
Resolves #73
=> [motion] Define 'sides' value for ray size.

motion-1/Overview.bs, motion-1/Overview.html
There were previously separate behaviors for lengths vs
percentages of offset-distance in
https://drafts.fxtf.org/motion-1/#calculating-the-computed-distance-along-a-path
This was problematic as calc() can combine the two.
resolves #74
=> [motion] computed distance now supports calc

motion-1/Overview.bs, motion-1/Overview.html
As an argument of ray paths, <size> supports
'sides', and does not support <length>, or
<length-percentage>{2}.
Thus linking to the CSS Images defintion of
<size> is not appropriate.
=> [motion] Link to Motion Path's size definition

geometry/Overview.bs
Fixes #120.
Tests: https://github.com/w3c/web-platform-tests/issues/5885
=> [geometry] Tighten up DOMMatrix's stringifier; throw for NaN/Infinity

motion-1/Overview.bs, motion-1/Overview.html
size is now required. The examples now show size explicitly.
The polar placement examples assume the rays begin at the center
of the body. We now make that explicit by setting left/top or by
setting offset-position.
=> [motion] Supply size in ray examples

geometry/Overview.bs
This is consistent with other APIs such as JS's Map, Set, and
Array.prototype.includes.
Fixes #152.
=> [geometry] Treat 0 and -0 as equal throughout

geometry/Overview.bs
Also refactor into a common algorithm for both DOMMatrix constructor
and setMatrixValue, since they kept getting out of sync. Explicitly
hook into the css-syntax "parse something according to a CSS grammar".
Fixes #149. Fixes #144.
Tests: https://github.com/w3c/web-platform-tests/pull/5902
=> [geometry] Parse as CSS 'transform' instead of SVG transform=""

geometry/Overview.bs
Also mark non-normative sections as such.
~~This is blocked on https://github.com/w3c/fxtf-drafts/pull/153.~~
---
When this has landed I think it's time for a new WD... cc @plehegar
=> [geometry] Update the Changes section

motion-1/Overview.bs
The default offset-rotate is auto (rotate with the path)
and the default offset-position is auto (path begins at
position from layout or left/top if position: absolute).
The examples that place squares using polar positioning
assume the paths start at the center at that no rotation
occurs.
We now set offset-position: 50% 50% and offset:rotate: 0deg
explicitly.
=> [motion] Specify offset-rotate 0deg in examples

motion-1/Overview.bs
offset-position not none, and/or offset-path not auto,
results in the creation of a stacking context and
containing block, per usual for transforms.
We no longer compare with opacity or exclude SVG.
The wording is now similar to that for the individual
transform properties
https://drafts.csswg.org/css-transforms-2/#individual-transforms
resolves #79
=> [motion] Create containing blocks

motion-1/Overview.bs
'offset-position' is ignored for circle and ellipse basic shapes with
explicit center positions, and for other types of basic shapes. If a
circle or ellipse basic shape has no explicit center position, the
shape is centered at the initial position of the path, as described
in 'offset-position'.
resolves #78
=> [motion] Interaction of offset-position and shapes

motion-1/Overview.bs
The offset-rotate example image has numbers centered in circles.
We use flexbox to center the numbers, horizontally and vertically.
=> [motion] Center numbers in circles

motion-1/Overview.bs, motion-1/images/normal-flow.svg
When a circle or ellipse has no explicit center, the center
is determined by offset-position. When offset-position is
auto, position is used.
(In the example, the margin-box has dimensions 343x151 px,
and the circle radius is 60% of 265px.)
=> [motion] Example basic shape with implicit center

motion-1/Overview.bs
If a basic shape is supplied without a geometry box,
border-box is used by default.
Minor typo corrections so bikeshed runs without error.
Resolves #189
=> [motion] Use border-box as default reference box

motion-1/Overview.bs, motion-1/images/position-absolute.svg, motion-1/images/position-scale.svg, motion-1/images/position-transform.svg
If offset-position is a position, the motion path translation (and
hence left/right/top/bottom if position is 'absolute') can be observed
if 'rotate' or 'scale' are set.
https://drafts.csswg.org/css-transforms-2/#ctm
If offset-path is a geometry-box, or a basic shape (other than a circle
or ellipse with implicit center), then the value of offset-position is
ignored and we have absolute positioning even if offset-position is
'auto' and position is 'static'.
https://drafts.fxtf.org/motion-1/#offset-path-property
offset-position and offset-anchor do not support the deprecated 3-value
syntax used by 'background-position'
https://lists.w3.org/Archives/Public/www-style/2017Mar/0054.html
position 'static' (the initial value) does not cause offset-position to
be ignored, just as it does not cause …
=> Clarify  motion path and position interaction

motion-1/Overview.bs
The initial direction describes how the position changes when
offset-distance is increasing from 0%.
The offset-rotate 'auto' rotation can be deduced from this.
inset() can have a border radius, we need to take that into
account in the initial position.
The initial direction was also discussed in #76
=> Simplify description of initial direction

motion-1/Overview.bs, motion-1/images/increase-size.svg
'smallest clipped area' gave no guidance when the path and the box
had zero area in common regarless of the value of offset-distance.
For example, this can occur when the path size is 0, or when
offset-anchor is substantially outside the box.
We now define the meaning of 'contain' by specifying that the path
size is minimally increased so that the box can be contained.
resolves #22
=> [motion-1] Clarify meaning of contain

motion-1/Overview.bs
A ray contain example had an unintended auto rotation as offset-rotate: 0deg was omitted.
The offset-anchor examples omitted % units.
The offset-rotate example needs reduced offset-distance as the placed circles were partially outside the path.
(See commit comments for full details.)
=> [motion-1] Minor corrections to examples

geometry/Overview.bs
See https://github.com/w3c/csswg-drafts/issues/1479
Tests: https://github.com/w3c/web-platform-tests/issues/6299
=> Revert "Kill DOMRectList"

geometry/Overview.bs
This is needed for CanvasRenderingContext2D's setTransform().
Fixes #210.
Tests: https://github.com/w3c/web-platform-tests/pull/7007
---
cc @dcrousso @junov @annevk @grorg
=> [geometry] Add a DOMMatrix2dInit dictionary type

geometry/Overview.bs
Match latest WebIDL spec[1]. This fixes #200.
[1] https://heycam.github.io/webidl/#Default
=> [geometry] Replace serializers with "[Default] toJSON()".

filter-effects/Overview.bs
Like gradients and transform, hue-rotate() accepts
unitless 0.
Test:
https://github.com/w3c/web-platform-tests/pull/7890
resolves #228
=> [filter-effects] hue-rotate() takes unitless zero

motion-1/Overview.bs, motion-1/images/initial-outside.svg
closest-side and farthest-side are perpendicular distances
measured between the initial position and the relevant sides.
When closest-side or farthest-side are used, and the initial
position is outside the box, the sides are considered to extend
indefinitely.
(When diagonal distances to corners are required, closest-corner
and farthest-corner can be used.)
=> [motion] Clarify meaning of closest-side

geometry/Overview.bs
Fixes #217.
---
cc @fserb @junov @smfr 
---
This does not need new tests, but needs a corresponding change for HTML. I can do that but will wait for this to have an approved review.
=> [geometry] Editorial: Use separate entry points instead of ignore3D

compositing-1/Overview.bs, compositing-2/Overview.bs
blend-mode, isolation-mode and composite-mode production rules now have
the 'prod' CSS class, for easier identification by tools.
resolves #302
=> [compositing] Use prod class for production rules

compositing-1/Overview.bs, compositing-2/Overview.bs
=> Replace links to w3c copy of canvas spec with links to living WHATWG spec

geometry/Overview.bs
It is not necessary to mention that there are various other IDL methods in other specs which
return DOMRect or DOMRectReadOnly objects. The rect classes are well-defined on their own.
=> Remove sentence unnecessarily referencing "box types"

filter-effects/appendix/interfaces.md
SVGURIReference is an `interface mixin`, not an `interface`, so the operator is `includes` not `implements`.
Found this when cleaning up the SVG deps for https://github.com/web-platform-tests/wpt/issues/11796
=> Correct inclusion of SVGURIReference

filter-effects/Overview.bs
color-interpolation-filters has an initial value linearRGB,
as was specified in SVG 1.1 as as implemented in browsers.
Discussed in https://github.com/w3c/csswg-drafts/issues/3131
=> [filter-effects] initial value linearRGB

motion-1/Overview.bs
reverse is equivalent to auto 180deg.
The computed value only uses auto.
WPT https://github.com/web-platform-tests/wpt/pull/13820
=> [motion] reverse does not appear in computed value

filter-effects-2/Overview.bs
With this change, the spec is now explicit that the input image for the backdrop root image should be clipped to the border box of the element. Prior to this change, the spec was written such that the
entire backdrop image was to be used as the filter input. For filters that move pixels (e.g. blur), this
meant that neighboring content that is outside the bounds of the element would influence the filtered
content within the element's bounds.
This change is a good one for these reasons:
- It agrees more closely with existing Webkit/Safari behavior.
- It improves performance, by filtering fewer pixels in the
case of pixel-moving filters.
- Developers have been disappointed with the existing behavior
of bringing in pixels from outside the bounds of the
element, and have requested a way to …
=> Clip backdrop root (input) image to border box of element

filter-effects/Overview.bs
Link to HTML LS, rather than HTML 5.x, for definition of the `crossorigin` attribute.
(Also a bunch of trailing-whitespace cleanup, good to do but sorry for the noise in this PR, my editor does it automatically)
=> Link to crossorigin attr in HTML LS

css-masking-1/Overview.bs
Potentially CORS-enabled fetch should link to the Fetch specification, not HTML 5.x
=> [css-masking-1] update Fetch reference

geometry/Overview.bs
As [the prose](https://drafts.fxtf.org/geometry/#dom-dompointreadonly-matrixtransform) says it returns a new object.
=> [geometry] Add [NewObject] to matrixTransform

filter-effects-2/Overview.bs
Per [request from TAG](https://github.com/w3ctag/design-reviews/issues/353#issuecomment-530180965), I've added two more red "Issue" markers at the Backdrop Root definition, and the discussion of Backdrop Root Triggers.
=> Added more issue markers for the lack of consensus on backdrop root

compositing-2/Overview.bs
r? @chrishtr
Fixes https://github.com/w3c/fxtf-drafts/issues/380
I don't attempt to fix compositing-1 here, though I could.
Also, bikeshed was throwing up some warnings about some links, I fixed them by updating most CSS21 references.
I might bikeshedify more links later
=> Use bikeshed links for blend modes

compositing-1/Overview.bs, compositing-2/Overview.bs
=> Apply resolution of compositing for the root element

compositing-1/Overview.bs, compositing-2/Overview.bs
The background of the root element (if specified) should paint into the page group, and therefore any elements in the root stacking context/isolated group will blend with that color.
=> Fix text to specify correct blend-mode on the root element

geometry/Overview.bs
This follows the rough consensus reached in #222, as well as what WebKit
implements today.
Fixes #222.
----
Tests: ...
I'm be happy to implement this in Chrome. If this is deemed acceptable, I could just write the WPTs as part of the Chromium change.
=> [geometry-1] Define minimum and maximum as preferring NaN

motion-1/Overview.bs
This change corrects the syntax for the `<ray()>` and `<path()>` non-terminal component values as defined in point 4 of https://drafts.csswg.org/css-values-4/#component-types.
Fixes #410
=> [motion-1] Corrected <ray()> and <path()> type syntax

motion-1/Overview.bs
This fixes the linking to the definition of the `<size>` data type (see #411)
=> [motion-1] Fixed link to <size> definition in ray() syntax

motion-1/Overview.bs
Convert to width/height attributes like others in document. Flagged by HTML validator
=> [motion-1] fix: unitless image height

geometry/Overview.bs
Clarifies the behavior of e.g. matrix.transformPoint.
Resolves: #294, #359
=> Column vectors are pre-multiplied by matrices.

css-masking-1/Overview.bs
* Change group from CSSWG to fxtf because the issue links are not correct (see https://www.w3.org/TR/2021/CRD-css-masking-1-20210805/#issue-d0c561ed for an example).
* http -> https
=> [css-masking-1] Editorial fixes

fill-stroke/Overview.bs
This replaces "inline boxes" by "text" in the "Applies to" section of the property definition tables of Fill and Stroke 3 as of the resolution in https://github.com/w3c/csswg-drafts/issues/5303.
It fixes https://github.com/w3c/csswg-drafts/issues/6823.
Sebastian
=> [fill-stroke-3] Replace "inline boxes" by "text" in Applies to

compositing-2/Overview.bs, compositing-2/Overview.html
Fixes https://github.com/w3c/csswg-drafts/issues/6821.
Tests https://github.com/web-platform-tests/wpt/pull/31757.
This allows any two elements to be cross-faded together. More details: https://jakearchibald.com/2021/dom-cross-fade/.
I'm not really sure about the difference between "blend" and "composite", particularly since `globalCompositeOperation` in canvas includes both.
We might eventually get to the stage where `mix-blend-mode` and `globalCompositeOperation` have the same set of operations, which is kinda weird since they have different names.
=> [css-compositing-2] Add plus-lighter to mix-blend-mode and background-blend-mode

compositing-2/Overview.bs
The syntax for `rgb()` only allows _either_ all color components to be `<number>`s or `<percentage>` but not mix them. That means that `0` values must be written as `0%`.
This change fixes all occurrences of those erroneous uses of `rgb()` and by that fixes #456.
Sebastian
=> [compositing-2] Fixed examples with percentages in rgb() functions

css-masking-1/Overview.bs
`rect()` should be a `<reference>` to a production definition
=> [css-masking-1] Fix <'clip'> syntax

css-masking-1/Overview.bs
I think this is the last remaining occurrence of `<number-percentage>`.
Follow-up on: https://github.com/w3c/fxtf-drafts/commit/fe40e6efc92d644983f538cc72995cf73535ca8c
Related: https://github.com/w3c/csswg-drafts/issues/7727
=> [css-masking-1] No more <number-percentage> #7727

motion-1/Overview.bs
Moves path function to the basic-shape section as it's now one of the basic shapes.
Fixes https://github.com/w3c/fxtf-drafts/issues/493
=> [motion-1] Move path() to the <basic-shape> section.

motion-1/Overview.bs
Makes <ray-size> optional, defaulting to 'closest-side'.
It's done for the cases when 'offset-distance' is specified in pixels.
Fixes https://github.com/w3c/fxtf-drafts/issues/491
=> [motion-1] Make <ray-size> optional. Defaulting to 'closest-side'.

compositing-1/Overview.bs, compositing-2/Overview.bs, css-masking-1/Overview.bs
The basic syntax definition of `<blend-mode>` and `<mask-layer>` is rendered in browsers without a whitespace where the first line break of a `<pre>` appears in the Bikeshed source text:
```
<blend-mode> = ... |color-burn | ...
<mask-layer> = ... ||<repeat-style> || ...
```
I do not know why Bikeshed removes the line break therefore I am not sure this PR is appropriate.
---
`<blend-mode>` values have been grouped as in popular graphic design softwares.
---
**Aside**
I do not know if the missing whitespace is a syntax error, or if a css value definition parser should handle it.
`initial-value` (in `@property`) may support combinations in the future and authors may use line breaks in combinations.
The CSS value definition syntax may have to define if 1. one or more whitespaces and/or line …
=> [css-compositing][css-masking] Force rendering whitespaces around combinators

filter-effects/Overview.bs
This is part of specifying CSS ink overflow extent:
https://github.com/w3c/csswg-drafts/issues/8649
=> Specify ink overflow for blur() and drop-shadow()

filter-effects/Overview.bs
[`flood-opacity`](https://drafts.fxtf.org/filter-effects-1/#FloodOpacityProperty) is defined with `<alpha-value>` but its specified value must be clamped whereas there is interop for clamping the computed value, like for `opacity`.
I suggest to define `flood-opacity` with `<'opacity'>`.
Related: https://github.com/w3c/csswg-drafts/issues/8311
=> [filter-effects-1] Replace `<alpha-value>` with `<'opacity'>`

filter-effects-2/Overview.bs, filter-effects/Overview.bs, filter-effects/mathml/feConvolveMatrix07.mml
Adds the mirror edgemode described in #527 with an example showing how it extends an image. This is now used by backdrop-filter as per the resolution in #374.
=> [filter-effects] Add mirror edgeMode filter

compositing-2/Overview.bs, fill-stroke/Overview.bs, filter-effects-2/Overview.bs
- fixes #521
- replaces all occurrences of `Animatable` with `Animation type` as a property definition field
- replaces `no` with `not animatable` (as an `Animation type` value)
- `isolation` ***edit***: replaced with `discrete` (see following comment and https://github.com/w3c/fxtf-drafts/commit/402eece3e43edb5f52ac9a6c21f6e62bf2ed913d)
- replaces `no` with `discrete`
- `background-blend-mode`, `mix-blend-mode`
- `fill-break`, `stroke-break`
- `fill-origin`, `stroke-origin`
- `fill-repeat`, `stroke-repeat`
- `fill-rule`
- `stroke-align`
- `stroke-dash-justify`
- `stroke-linecap`
- `stroke-linejoin`
- `stroke-miterlimit`
- replaces `as repeatable list of integers` with `by computed value`
- `stroke-dashoffset`
- replaces `as repeatable list of *` with `as repeatable list`
- `fill-image`, …
=> Convert `Animatable` to `Animation type` prop definition field

compositing-1/Overview.bs, compositing-1/Overview.html
The canvas background is where the background for the \<html\> (or \<body\>!) element is drawn, and this clarifies that this is included in the root element group.
=> [compositing-1] Clarify the interaction between the Root Element Group and the canvas background.

css-masking-1/Overview.bs
This fixes https://github.com/w3c/csswg-drafts/issues/10456.
Sebastian
=> [css-masking-1][editorial] Fixed typos in example

filter-effects-2/Overview.bs
Fix bikeshed errors.
The command:
```
bikeshed spec filter-effects-2\Overview.bs
```
Throws errors:
```
LINE ~41: Section autolink [[filter-effects#animation-of-filters]] attempts to link to unversioned spec name 'filter-effects', but that spec is versioned as 'filter-effects-1' or 'filter-effects-2'. Please choose a versioned spec name.
LINE ~345: Section autolink [[filter-effects#tainted-filter-primitives]] attempts to link to unversioned spec name 'filter-effects', but that spec is versioned as 'filter-effects-1' or 'filter-effects-2'. Please choose a versioned spec name.
```
Choose spec version.
=> [filter-effects-2] Fix spec version in link

filter-effects/Overview.bs
Fix bikeshed errors.
The command:
```
bikeshed spec filter-effects\Overview.bs
```
Throws errors:
```
LINE 728:11: Character reference '&lt' didn't end in ;.
LINE 732:11: Character reference '&lt' didn't end in ;.
```
HTML comment open tag is broken.
=> [filter-effects] Fix code example

filter-effects-2/Overview.bs
Fix bikeshed errors.
The command:
```
bikeshed spec filter-effects-2\Overview.bs
```
Throws errors:
```
LINE 229:3: Spurious / in <img>.
LINE 231:3: Spurious / in <img>.
LINE 240:3: Spurious / in <img>.
LINE 246:3: Spurious / in <img>.
LINE 252:3: Spurious / in <img>.
LINE 255:3: Spurious / in <img>.
LINE 275:3: Spurious / in <img>.
LINE 277:3: Spurious / in <img>.
LINE 300:3: Spurious / in <img>.
LINE 302:3: Spurious / in <img>.
```
=> [filter-effects-2] Fix spurious / in <img>

compositing-2/Overview.bs
Fix bikeshed errors.
The command:
```
bikeshed spec compositing-2\Overview.bs
```
Throws errors:
```
LINE 160:1: Spurious / in <img>.  
LINE 173:1: Spurious / in <img>.  
LINE 197:1: Spurious / in <img>.  
LINE 222:1: Spurious / in <img>.  
LINE 254:1: Spurious / in <img>.  
LINE 334:1: Spurious / in <img>.  
LINE 476:1: Spurious / in <img>.  
LINE 499:1: Spurious / in <img>.  
LINE 536:1: Spurious / in <img>.  
LINE 572:1: Spurious / in <img>.  
LINE 643:1: Spurious / in <img>.  
LINE 653:1: Spurious / in <img>.  
LINE 754:30: Spurious / in <img>. 
LINE 832:1: Spurious / in <img>.  
LINE 843:1: Spurious / in <img>.  
LINE 857:1: Spurious / in <img>.  
LINE 871:1: Spurious / in <img>.  
LINE 884:1: Spurious / in <img>.  
LINE 898:1: Spurious / in <img>.  
LINE 911:1: Spurious / in <img>. …
```
=> [compositing-2] Fix spurious / in <img>

compositing-1/Overview.bs, compositing-2/Overview.bs
To unify the specification titles, I've added the word "Module" to the Compositing specs.
See also https://github.com/w3c/csswg-drafts/pull/12866 and https://github.com/w3c/csswg-drafts/pull/12879.
Sebastian
=> [compositing-1][compositing-2] Added "Module" to spec title
