w3c/fxtf-drafts

- motion-1/Overview.bs
- motion-1/Overview.html
offset-anchor value can be auto | <position>
Resolves #39
> [css-motion] auto is permitted value for offset-anchor

- motion-1/Overview.bs
- motion-1/Overview.html
basic-shapes and path strings can animate, in addition to angles.
Resolves Issue #33
> [css-motion] offset-path can animate more than angles

- motion-1/Overview.bs
- motion-1/Overview.html
offset-rotation may be:
- auto/reverse
- &lt;angle>
- both auto/reverse and &lt;angle>, in any order.
Resolves #6
> [css-motion] No need to specify both auto/reverse and angle

- motion-1/Overview.bs
- motion-1/Overview.html
https://drafts.csswg.org/css-transforms-1/#transform-rendering
"The coordinate space is a coordinate system with two axes: the X axis increases horizontally to the right; the Y axis increases vertically downwards."
Thus the negative y-axis points to the upper side.
> [css-motion]: The negative y-axis points to the upper side

- motion-1/Overview.bs
Dropping `<br>` since it's not needed. Tweak a few prepositions and such.
> [motion] Trivial wording tweaks

- motion-1/Overview.bs
- motion-1/Overview.html
If the initial position is on an edge, the path is zero length.
Resolves #62
> [motion] Clarify note about closest-side

- motion-1/Overview.bs
- motion-1/Overview.html
- motion-1/images/offset_anchor_auto.svg
- motion-1/images/offset_anchor_center.svg
When offset-anchor is center, the element is centered at offset-position.
An important use-case for offset-anchor 'auto' is when offset-position is
expressed in percentages.
> [motion] Add examples of offset-anchor with offset-position and no path

- motion-1/Overview.bs
- motion-1/Overview.html
- motion-1/images/offset-distance-closed.svg
- motion-1/images/offset-distance-unclosed.svg
We clamp when we have an unclosed interval.
We use modulus when we have a closed loop.
> [motion] Examples of offset-distance computation

- motion-1/Overview.bs
- motion-1/Overview.html
SVG specifies the behavior for animation of path data:
https://www.w3.org/TR/SVG/paths.html#DAttribute
We now link to that specification.
Issue raised by Brian Birtles:
https://groups.google.com/a/chromium.org/d/msg/blink-dev/_DPl-JG6bV8/zXf2q9jgDwAJ
> Link to definition of animation for path() data.

- geometry/Overview.bs
> [geometry] Remove inline issue about experimental API shape

- geometry/Overview.bs
Fixes #145.
Tests: https://github.com/w3c/web-platform-tests/issues/5895
---
cc @chrishtr @foolip
> [geometry] Limit DOMMatrix's special stringifier to Window

- geometry/Overview.bs
> [geometry] Define serialize/deserialize steps

- geometry/Overview.bs
Fixes #161.
Tests: https://github.com/w3c/web-platform-tests/pull/5937
> [geometry] Do not structured serialize -0 for m13 of a 2d matrix

- geometry/Overview.bs
See https://github.com/heycam/webidl/issues/362
> [geometry] Use [LegacyWindowAlias] for SVG* and WebKitCSSMatrix

- geometry/Overview.bs
~~Whether to have aliases for SVG* is an open issue,~~ see #163.
> [geometry] Add a Historical section discussing old interfaces

- motion-1/Overview.bs
offset-path may be a ray. We now link to the definition of ray.
> [motion] Link to definition of ray

- geometry/Overview.bs
> [geometry] Define better how to transform a point with a matrix

- geometry/Overview.bs
See https://lists.w3.org/Archives/Public/public-fx/2017JulSep/0000.html
> [geometry] Update editor

- geometry/Overview.bs
> [geometry] Editorial: Fix incorrect examples

- motion-1/Overview.bs
This specification introduces no new security or privacy considerations.
(same wording as [CSS Transform Module Level 2](https://drafts.csswg.org/css-transforms-2/#priv-sec))
> [motion-1] Privacy and Security paragraph

- filter-effects/appendix/interfaces.md
@tobie could you please review?
> [filter-effects] Use mixin syntax. Issue #233.

- filter-effects/Overview.bs
Replace 'attribtue' with 'attribute'
resolves #260
> [filter-effects] Fix small typo - attribtue

- geometry/Overview.bs
Add "must" in fromPoint() definition on DOMPoint.
> [geometry] Add a missing "must"

- geometry/Overview.bs
(See also https://github.com/heycam/webidl/issues/365)
> [geometry] Add explicit [Exposed] to DOMRectList

- geometry/Overview.bs
> [geometry] Remove redundant originZ check

- .gitignore
- motion-1/Overview.bs
Computed offset-distance is a computed <length-percentage> value.
> [motion] computed <length-percentage> value

- geometry/Overview.bs
Required after heycam/webidl#750. (Found from web-platform-tests/wpt#18382)
Closes #356
> [geometry] Add default dictionary value

- filter-effects/appendix/interfaces.md
> Add [Exposed=Window] where still missing

- filter-effects/appendix/interfaces.md
See https://github.com/heycam/webidl/pull/906.
> Replace void with undefined in Web IDL

- filter-effects-2/Overview.bs
We need to reference this in the view-transitions spec.
> Export backdrop root

- css-masking-1/Overview.bs
> Replace <geometry-box> with <coord-box> mask-origin & mask-clip

- css-masking-1/Overview.bs
> remove margin-box from description mask-clip

- css-masking-1/Overview.bs
> [css-masking] Make interpolation of mask-border-* consistent with border-image-*
